"""Set B: a second, larger labelled query set for the Basilisk source index.

WHY A SECOND FILE, NOT AN EXTENSION OF SET A
    Set A (`basilisk_source_queries.py`) is frozen -- its ids, its splits, its
    26 questions. This file adds ~98 more under two deliberate design changes
    that do not retrofit cleanly onto set A's shape, so they live here instead:

    1. GOLD IS SET-VALUED BY DEFAULT. A real question often has several right
       answers -- "surface tension with a contact angle" is genuinely served by
       both `tension.h` and `contact.h`. Every gold list below names every
       header that legitimately answers the question, not the one file that
       makes scoring convenient. Single-element gold survives only where the
       question truly has one answer -- chiefly the NAME control tier.

    2. A NEW TIER, STACK. NAME/CONCEPT/ERROR/RULE/KNOB (set A's scheme) never
       asks "what do I combine, and does order matter?" -- the question where a
       filename-shaped retriever is structurally blind, because the answer is a
       SET of headers, in no one of which the combination is named. STACK fills
       that gap. Every STACK gold set below is a combination actually observed
       in the corpus (a `#include` sequence in a real test/example, or an
       explicit cross-reference in a header's own prose) -- never a plausible
       guess at what "should" compose.

COVERAGE, NOT A MULTIPHASE SHOWCASE
    An earlier draft of this file weighted the question set toward multiphase
    flow (VOF, surface tension, contact lines, droplets). That was corrected:
    this tool has to serve every Basilisk user, and a set skewed to one
    subfield measures the index on one corner of the corpus and says nothing
    about the rest. What follows instead spreads across what `src/` actually
    contains -- shallow-water/Saint-Venant, the layered ocean solver (and its
    GOTM turbulence coupling), compressible flow, general embedded boundaries,
    electrohydrodynamics, grid/AMR/MPI/GPU machinery, and I/O/visualisation --
    with multiphase flow present as roughly a fifth of CONCEPT and of STACK,
    not their center. `ast/` and `gl/` (compiler internals and the OpenGL
    rendering backend) are deliberately under-represented relative to their
    raw file count: both are large by header count but almost entirely
    machinery nobody queries in English while solving a physics problem.
    `gotm/` is the same story at greater scale -- roughly 60 of the 310
    headers are Fortran-to-C bindings generated by `gotm.awk`, declared
    independent of Basilisk in their own top comment (`gotm/common.h`). No
    working engineer greps for `__turbulence_MOD_tke`; the real, queryable
    surface is the Basilisk-side integration point, `layered/gotm.h`, which
    this file does cover (see STACK `sb07`).

VERIFICATION, THE SAME DISCIPLINE AS SET A
    Every gold path was checked against the corpus. Every STACK and RULE
    claim was checked against actual source: an `#include` sequence in a real
    test/example case, or a header's own prose making an explicit claim about
    itself or another file. Where a plausible-sounding combination could not be
    found in the corpus, it was discarded rather than guessed -- the discards
    are listed at the bottom of this docstring for the record.

DISCARDED (drafted, then rejected for lack of evidence)
    - "can contact.h's contact angle be combined with an embedded boundary's
      cs/fs fields directly (not just the domain-wall case)?" -- no file in
      the corpus combines `contact.h` and `embed.h`, and neither header
      references the other's mechanism. Kept only as the negative RULE `rb01`
      (verified as an absence), not stretched into a fabricated positive claim.
    - "does grid/balance.h expose a tunable imbalance threshold I can set from
      user code?" -- no such symbol was found in `grid/tree-mpi.h` or
      `grid/balance.h`; discarded rather than invented as a KNOB.
    - "can a dump from the tree grid be restored with a different mesh
      resolution N?" -- the restore-time checks found in `output.h` compare
      process count and file version, not N; a claim about resolution
      portability was not evidenced either way, so it was dropped instead of
      guessed as true or false.
    - "does layered/isopycnal.h forbid combining with layered/entrainment.h?"
      -- both are used in `examples/ocean.h` together, so the intended
      "forbid" framing was false; rewritten as the (positive) fact that
      isopycnal buoyancy is a special case of the general module (`rb06`)
      instead of the discarded incompatibility claim.

WHAT A GOLD ANSWER IS
    Same contract as set A: the file(s) a correct answer must name, relative
    to Basilisk's `src/`. Where more than one is listed, ANY of them at rank 1
    counts as a hit, and for STACK the gold set is the SET a correct answer
    must name in full (a partial subset is not a hit).
"""
from __future__ import annotations

#: Extends set A's TIERS with the new combinatorial tier. Set A's own TIERS
#: dict is untouched -- this is this file's own copy, used by this file's test.
TIERS_B = {
    "nb": "NAME",     # control, same role as set A's "n"
    "cb": "CONCEPT",  # English from outside Basilisk's vocabulary
    "sb": "STACK",    # NEW: "I need X and Y together -- what, and in what order?"
    "rb": "RULE",     # "am I allowed to / should I?" -- a constraint, not a file
    "eb": "ERROR",    # a string the agent did not choose
    "kb": "KNOB",     # "how do I change/disable this"
}

# =============================================================================
# NAME -- control tier. Exact identifier or filename; ripgrep should win.
# Spread across areas rather than clustered in one: VOF geometry, shallow
# water, tsunami sources, grid/AMR machinery, compressible EOS, EHD, the
# layered ocean solver, I/O, and memory diagnostics.
# =============================================================================
NAME_B = [
    # mycs is genuinely defined three times over (1D inline, 2D, 3D) -- a
    # NAME query where the honest gold is still a set, not a single file.
    ("nb01", "mycs", ["fractions.h", "myc.h", "myc2d.h"]),
    ("nb02", "green-naghdi.h", ["green-naghdi.h"]),
    ("nb03", "okada.h", ["okada.h"]),
    ("nb04", "riemann.h", ["riemann.h"]),
    ("nb05", "grid/balance.h", ["grid/balance.h"]),
    ("nb06", "compressible/Mie-Gruneisen.h", ["compressible/Mie-Gruneisen.h"]),
    ("nb07", "ehd/stress.h", ["ehd/stress.h"]),
    ("nb08", "layered/coriolis.h", ["layered/coriolis.h"]),
    ("nb09", "vtk.h", ["vtk.h"]),
    ("nb10", "grid/mtrace.h", ["grid/mtrace.h"]),
]

# =============================================================================
# CONCEPT -- the target tier. Practice-realistic English a working engineer
# would actually type mid-task, sharing no 3+ distinctive words with the gold
# file. Multiphase flow (VOF/tension/contact/droplets) is capped at ~1/5 of
# this tier on purpose; the rest spreads across shallow-water/tsunami/ocean,
# compressible flow, general embedded boundaries, EHD, and grid/HPC machinery.
# =============================================================================
CONCEPT_B = [
    # --- multiphase flow (6 of 32 ~ 19%) ---------------------------------
    ("cb01", "why does my droplet develop spurious velocities even though "
     "nothing is pushing it", ["test/spurious.c"]),
    ("cb02", "count how many separate droplets came out after a liquid jet "
     "breaks up", ["tag.h", "examples/atomisation.c"]),
    ("cb03", "stop two nearby bubbles in my simulation from merging into one",
     ["no-coalescence.h"]),
    ("cb04", "set a fixed wetting angle where my liquid interface meets a "
     "solid wall", ["contact.h"]),
    ("cb05", "my drop keeps drifting on its own because of a temperature "
     "difference along its surface", ["test/marangoni.c", "integral.h"]),
    ("cb06", "a dissolved gas is slowly leaking out of a moving bubble into "
     "the surrounding liquid", ["henry.h"]),
    # --- shallow water / ocean / tsunami / layered solver (8) ------------
    ("cb07", "turn an earthquake fault rupture into an initial wave for a "
     "tsunami run", ["okada.h"]),
    ("cb08", "check my simulated tsunami's arrival times against real "
     "deep-ocean buoy records", ["gauges.h", "examples/tohoku.c"]),
    ("cb09", "add the Earth's rotation and bottom drag to a large-scale "
     "ocean current model", ["layered/coriolis.h"]),
    ("cb10", "mix temperature or salinity vertically through the water "
     "column over time", ["layered/diffusion.h"]),
    ("cb11", "capture dispersive wave effects that the plain shallow-water "
     "equations can't represent", ["green-naghdi.h"]),
    ("cb12", "put the ocean model's layers back onto evenly spaced vertical "
     "levels after they've drifted", ["layered/remap.h"]),
    ("cb13", "force a fixed flow rate through a river or channel outlet",
     ["discharge.h"]),
    ("cb14", "reproduce a classic wind-driven upper-ocean mixing case with a "
     "turbulence closure", ["test/ows_papa.c", "layered/gotm.h"]),
    # --- compressible flow (5) --------------------------------------------
    ("cb15", "simulate a shock wave travelling through a compressible gas",
     ["compressible.h", "test/explosion.c"]),
    ("cb16", "model an underwater explosion where the shock crosses two "
     "fluids with different equations of state",
     ["compressible/two-phase.h", "compressible/Mie-Gruneisen.h"]),
    ("cb17", "simulate a slow buoyant plume without resolving sound waves",
     ["all-mach.h"]),
    ("cb18", "add heat transfer between the two fluids in a compressible "
     "shock problem", ["compressible/thermal.h"]),
    ("cb19", "model a fluid that barely compresses, like liquid water under "
     "high pressure, with a stiffened-gas equation of state",
     ["compressible/NASG.h"]),
    # --- embedded boundaries, general (5) ---------------------------------
    ("cb20", "solve an electrostatics or heat-conduction problem on a domain "
     "with an oddly shaped boundary", ["embed.h", "poisson.h"]),
    ("cb21", "simulate flow through a random packing of small solid "
     "obstacles", ["embed.h", "test/porous.c"]),
    ("cb22", "run an axisymmetric case where the wall is a complicated "
     "embedded shape, not a plain boundary", ["embed.h", "axi.h"]),
    ("cb23", "simulate 3D flow past a sphere with the mesh refined only near "
     "its surface", ["grid/octree.h", "embed.h"]),
    ("cb24", "reconstruct a solid shape from a CAD or STL file to use as an "
     "obstacle", ["distance.h", "fractions.h"]),
    # --- electrohydrodynamics (3) ------------------------------------------
    ("cb25", "compute the electric-field force pulling on a fluid interface",
     ["ehd/stress.h"]),
    ("cb26", "model ions migrating and building up a charge layer near an "
     "electrode", ["ehd/pnp.h"]),
    ("cb27", "a droplet stretches into an egg or pancake shape under a "
     "strong applied voltage", ["test/taylor.c"]),
    # --- grid / AMR / HPC machinery (5) --------------------------------
    ("cb28", "figure out why my long-running simulation keeps using more "
     "and more memory", ["grid/mtrace.h"]),
    ("cb29", "have a queued cluster job save its state and exit cleanly "
     "before the walltime runs out", ["maxruntime.h"]),
    ("cb30", "watch a simulation update live in a web browser while it "
     "runs", ["display.h"]),
    ("cb31", "I need a generic conservation-law solver for my own system of "
     "equations, not one of the built-in physics modules", ["conservation.h"]),
    ("cb32", "log per-timestep solver statistics like multigrid iteration "
     "counts and parallel speed", ["navier-stokes/perfs.h"]),
]

# =============================================================================
# STACK -- NEW TIER, the most valuable one. "I need X and Y together; what do
# I include, and in what order?" Gold is the SET of headers that must be
# combined -- verified against an actual `#include` sequence in a real
# test/example case, or an explicit textual cross-reference. Multiphase flow
# is again capped at roughly a fifth.
# =============================================================================
STACK_B = [
    # --- multiphase flow (5 of 23 ~ 22%) ---------------------------------
    ("sb01", "I need a fixed contact angle at a wall AND surface tension on "
     "the same interface -- what do I include, and in what order?",
     ["contact.h", "vof.h", "tension.h"]),
    ("sb02", "I want a rising bubble driven by buoyancy expressed as an "
     "interfacial force, not gravity acting everywhere -- what goes "
     "together?", ["navier-stokes/centered.h", "two-phase.h", "reduced.h"]),
    ("sb03", "my two-phase flow has a huge density ratio and develops "
     "spurious velocity spikes near the interface -- what extra module "
     "changes the advection scheme?",
     ["navier-stokes/centered.h", "two-phase.h",
      "navier-stokes/conserving.h"]),
    ("sb04", "I want the coupled VOF/levelset interface method together "
     "with the integral surface-tension formulation",
     ["two-phase-clsvof.h", "integral.h", "curvature.h"]),
    ("sb05", "I want my VOF tracer to stop separate droplets from merging "
     "automatically -- what do I add on top of the standard two-phase "
     "setup?", ["two-phase.h", "no-coalescence.h"]),
    # --- shallow water / ocean / layered solver (6) -----------------------
    ("sb06", "I need a tsunami source from a fault rupture and gauge time "
     "series to compare it against -- what two modules?",
     ["okada.h", "gauges.h"]),
    ("sb07", "I want a k-epsilon-style turbulence closure driving vertical "
     "mixing in my layered ocean model", ["layered/hydro.h",
     "layered/gotm.h"]),
    ("sb08", "I need a rotating, implicit-free-surface ocean model -- what "
     "headers, and does the order matter?",
     ["layered/hydro.h", "layered/implicit.h", "layered/coriolis.h"]),
    ("sb09", "I want dispersive, non-hydrostatic waves in the multilayer "
     "solver, with the layers remapped back to sigma coordinates",
     ["layered/hydro.h", "layered/nh.h", "layered/remap.h"]),
    ("sb10", "I'm setting up a lock-exchange gravity current in the "
     "multilayer solver -- buoyancy plus vertical remapping",
     ["layered/hydro.h", "layered/dr.h", "layered/remap.h"]),
    ("sb11", "I want surface tension in a free-surface meniscus problem "
     "solved implicitly, in the layered solver",
     ["layered/hydro-tension.h", "layered/implicit.h"]),
    # --- compressible flow (3) ---------------------------------------------
    ("sb12", "a compressible two-phase shock problem with a Mie-Gruneisen "
     "equation of state for each fluid -- what two files?",
     ["compressible/two-phase.h", "compressible/Mie-Gruneisen.h"]),
    ("sb13", "a compressible gas bubble collapsing in a liquid, with surface "
     "tension and an equation of state -- what four files?",
     ["compressible/two-phase.h", "compressible/Mie-Gruneisen.h",
      "tension.h", "compressible/tension.h"]),
    ("sb14", "compressible two-phase flow with thermal effects -- which "
     "equation-of-state module is it paired with?",
     ["compressible/NASG.h", "compressible/thermal.h"]),
    # --- electrohydrodynamics (2) --------------------------------------
    ("sb15", "a droplet deforming under an applied electric field -- which "
     "electrohydrodynamic modules, plus the interface tracker?",
     ["ehd/implicit.h", "ehd/stress.h", "vof.h", "tension.h"]),
    ("sb16", "ion transport and diffusion near a charged electrode",
     ["ehd/pnp.h", "diffusion.h"]),
    # --- embedded boundaries, general (3) --------------------------------
    ("sb17", "a Poisson problem with Dirichlet or Neumann boundary "
     "conditions on a complex-shaped domain", ["embed.h", "poisson.h"]),
    ("sb18", "an embedded boundary combined with an axisymmetric grid",
     ["embed.h", "axi.h"]),
    ("sb19", "a 3D adaptive mesh with an embedded spherical obstacle",
     ["grid/octree.h", "embed.h"]),
    # --- rheology (2) ---------------------------------------------------
    ("sb20", "a viscoelastic drop deforming in a Couette shear flow -- what "
     "three headers?", ["two-phase.h", "log-conform.h", "tension.h"]),
    ("sb21", "an axisymmetric viscoelastic drop hitting a solid surface",
     ["axi.h", "two-phase.h", "log-conform.h", "curvature.h"]),
    # --- general numerics / geometry (2) ---------------------------------
    ("sb22", "implicit diffusion of a scalar tracer, solved with the "
     "multigrid pressure-solver machinery", ["diffusion.h", "poisson.h"]),
    ("sb23", "turn a CAD or STL model into a distance field and then a "
     "volume fraction", ["distance.h", "fractions.h"]),
]

# =============================================================================
# RULE -- "am I allowed to / should I?" The answer is a constraint about the
# source, which no grep returns. Every claim below is grounded in an explicit
# textual cross-reference, an observed (or absent) co-occurrence, or a
# specific code check -- not in what "should" be true.
# =============================================================================
RULE_B = [
    # --- multiphase flow (4) ------------------------------------------
    ("rb01", "can I combine a wall contact angle with an embedded (cut-cell) "
     "boundary, or only with a plain domain wall?", ["contact.h"]),
    ("rb02", "will the standard surface-tension module handle a "
     "surface-tension coefficient that varies in space (e.g. a Marangoni "
     "gradient), or do I need the integral formulation instead?",
     ["tension.h", "integral.h"]),
    ("rb03", "for the best mass conservation, should I use the pure "
     "levelset two-phase solver or the coupled VOF/levelset one?",
     ["two-phase-levelset.h", "two-phase-clsvof.h"]),
    ("rb04", "can the momentum-conserving VOF advection module be used with "
     "a single-phase solver, or does it require two-phase.h?",
     ["navier-stokes/conserving.h", "two-phase.h"]),
    # --- shallow water / ocean (4) -----------------------------------
    ("rb05", "for a new shallow-water project, should I start from the "
     "classic Saint-Venant solver or the multilayer solver?",
     ["saint-venant.h", "layered/hydro.h"]),
    ("rb06", "is isopycnal-layer buoyancy a completely separate model from "
     "the general layered buoyancy module, or a special case of it?",
     ["layered/isopycnal.h", "layered/dr.h"]),
    ("rb07", "does surface tension in the multilayer solver only work with "
     "the implicit free-surface extension, or also with the non-hydrostatic "
     "one?", ["layered/hydro-tension.h", "layered/implicit.h",
              "layered/nh.h"]),
    ("rb08", "does the multilayer solver include the Earth's rotation by "
     "default, or must I add it explicitly?",
     ["layered/hydro.h", "layered/coriolis.h"]),
    # --- compressible flow (2) ---------------------------------------
    ("rb09", "once I add thermal effects to the compressible two-phase "
     "solver, do I keep the same equation of state or switch to a "
     "different one?", ["compressible/NASG.h", "compressible/thermal.h"]),
    ("rb10", "which equation of state is the compressible two-phase solver "
     "normally paired with when there's no thermal extension?",
     ["compressible/Mie-Gruneisen.h", "compressible/two-phase.h"]),
    # --- grid / AMR / parallelism (4) ---------------------------------
    ("rb11", "does the default (non-adaptive) grid support adapt_wavelet, "
     "or do I need a different grid type?",
     ["grid/multigrid.h", "grid/tree-common.h"]),
    ("rb12", "does the GPU grid backend support the same adaptive tree "
     "refinement as the CPU code?", ["grid/gpu/grid.h"]),
    ("rb13", "if my adaptive mesh becomes unbalanced across MPI ranks, do I "
     "have to rebalance it myself?", ["grid/tree.h", "grid/balance.h"]),
    ("rb14", "can I restart a run from a dump file using a different number "
     "of MPI processes than it was written with?", ["output.h"]),
    # --- misc (4) -----------------------------------------------------
    ("rb15", "does curvature() need me to compute the height functions "
     "myself first, or does it do that internally?", ["curvature.h"]),
    ("rb16", "is the lambda2 vortex-identification criterion meaningful in "
     "a 2D simulation?", ["lambda2.h", "examples/bubble.c"]),
    ("rb17", "does the layered solver's vertical remapping use its own "
     "numerics, or does it depend on an external library?",
     ["layered/remap.h", "ppr/ppr.h"]),
    ("rb18", "do embedded boundaries need more ghost cells than a plain "
     "simulation, or is the default enough?",
     ["embed.h", "grid/multigrid.h"]),
]

# =============================================================================
# ERROR -- a string the agent did not choose. Every one below was found
# verbatim in the corpus (grep the quoted substring to re-verify).
# =============================================================================
ERROR_B = [
    ("eb01", "convergence for %s not reached after %d iterations",
     ["poisson.h"]),
    ("eb02", "fractions_cleanup() did not converge after", ["embed.h"]),
    ("eb03", "draw_vof(): no field named", ["draw.h"]),
    ("eb04", "Input file is not a valid STL file", ["distance.h"]),
    ("eb05", "trying to modify a constant field", ["grid/cartesian-common.h"]),
    ("eb06", "save(): unknown format", ["view.h"]),
    ("eb07", "tree: N must be a power-of-two", ["grid/tree.h"]),
    ("eb08", "restore(): error: file version mismatch", ["output.h"]),
    ("eb09", "restore(): error: the number of processes don't match",
     ["output.h"]),
    ("eb10", "grid depths do not match. Aborting.", ["grid/multigrid.h"]),
]

# =============================================================================
# KNOB -- "how do I turn this off / point it somewhere else."
# =============================================================================
KNOB_B = [
    ("kb01", "my simulation is unstable -- how do I tighten the CFL number "
     "so it takes smaller steps?",
     ["navier-stokes/centered.h", "timestep.h"]),
    ("kb02", "how do I switch from the default arithmetic mean to a "
     "harmonic mean for density/viscosity across an interface?",
     ["two-phase-generic.h"]),
    ("kb03", "how do I let the pressure solver run more iterations before "
     "giving up instead of printing a convergence warning?", ["poisson.h"]),
    ("kb04", "how do I change the color palette used when rendering a "
     "field?", ["draw.h"]),
    ("kb05", "how do I make a long HPC job checkpoint and exit cleanly "
     "before the queue kills it?", ["maxruntime.h"]),
]

ALL_B = NAME_B + CONCEPT_B + STACK_B + RULE_B + ERROR_B + KNOB_B

#: Stratified per tier, roughly one third, ids listed literally -- a
#: hash-based split would silently reshuffle whenever a query is added.
#:   NAME_B:    3 of 10  held out (nb02, nb05, nb08)
#:   CONCEPT_B: 11 of 32 held out (cb02, cb05, cb08, cb11, cb14, cb17, cb20,
#:              cb23, cb26, cb29, cb32)
#:   STACK_B:   8 of 23  held out (sb02, sb05, sb08, sb11, sb14, sb17, sb20,
#:              sb23)
#:   RULE_B:    6 of 18  held out (rb02, rb05, rb08, rb11, rb14, rb17)
#:   ERROR_B:   3 of 10  held out (eb02, eb05, eb08)
#:   KNOB_B:    2 of 5   held out (kb02, kb05)
HELD_OUT_IDS_B = frozenset({
    "nb02", "nb05", "nb08",
    "cb02", "cb05", "cb08", "cb11", "cb14", "cb17", "cb20", "cb23", "cb26",
    "cb29", "cb32",
    "sb02", "sb05", "sb08", "sb11", "sb14", "sb17", "sb20", "sb23",
    "rb02", "rb05", "rb08", "rb11", "rb14", "rb17",
    "eb02", "eb05", "eb08",
    "kb02", "kb05",
})

HELD_OUT_B = [q for q in ALL_B if q[0] in HELD_OUT_IDS_B]
DEVELOPMENT_B = [q for q in ALL_B if q[0] not in HELD_OUT_IDS_B]
